export interface Movie {
  id: number;
  title: string;
  original_title?: string;
  overview: string;
  poster_path: string;
  backdrop_path: string;
  release_date: string;
  vote_average: number;
  vote_count: number;
  runtime?: number;
  genres: { id: number; name: string }[];
  director?: string;
  cast?: { id: number; name: string; character: string; profile_path?: string }[];
  trailer_key?: string; // YouTube video key
  tagline?: string;
  certification?: string;
  status?: string;
  popularity?: number;
  surpriseScore?: number;
  editorialBadge?: string;
}

export const MOCK_MOVIES: Movie[] = [
  {
    id: 693134,
    title: "Dune: Part Two",
    tagline: "Long live the fighters.",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAnHK4LtXnhfEPvv4hWcJKtFQD-R3tgAsz5l02lEyCVhr7S9o1WH5YWueKE9oQcZSfRLzdBnQd7gjio7BjvJiWK6cck1EWMICggp6Brcp4PRGbo2I2e4rSFf6s9kruwz64BWeWNuyiGhJwPLeG4ptpwm1s9Vnbys-pUuYP_r1PO9_HSoN3ORLgx6BrExrSBgT0DWIoBJ0CUvpVbjK33ynkZvyTzjQRQkUzut7NIPqhO49l1wF0dXAsN",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuC_sqhp6dCUUe8jJtVN1p_rpjdcVzZJjrhS618IqSrhkGS9zsZ9_iQT72sWuth1mZU3o-T1RZKzMGqh7o3LveAZgX7pGe-BTPuZOvyozhBtepABQyuqf_ase3dX8p1m7uOxP3BCYex3-XOmU8aOJ1AM-jXD55RJNVOE9lvRN-R6xAKEVZr1FUr7RcAqmJ7X08SpRc4pilejd1BGQ0vzl0WYI9ZKe8MG9eSvstGg9CaGX-lgCvovIx6J",
    release_date: "2024-03-01",
    vote_average: 8.6,
    vote_count: 5120,
    runtime: 166,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 12, name: "Adventure" }, { id: 18, name: "Drama" }],
    director: "Denis Villeneuve",
    cast: [
      { id: 1190668, name: "Timothée Chalamet", character: "Paul Atreides", profile_path: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150" },
      { id: 505710, name: "Zendaya", character: "Chani", profile_path: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150" },
      { id: 1373737, name: "Rebecca Ferguson", character: "Lady Jessica", profile_path: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150" },
      { id: 933238, name: "Austin Butler", character: "Feyd-Rautha Harkonnen", profile_path: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150" },
      { id: 74541, name: "Florence Pugh", character: "Princess Irulan", profile_path: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150" }
    ],
    trailer_key: "Way9Dexny3w",
    certification: "PG-13",
    editorialBadge: "Trending #1 Today",
    popularity: 98.5
  },
  {
    id: 157336,
    title: "Interstellar",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    overview: "When Earth becomes uninhabitable in the near future due to global crop blight and severe dust storms, a widowed former NASA pilot and farmer, Joseph Cooper, is tasked to pilot the spacecraft Endurance. Along with a dedicated team of elite scientists and researchers, he embarks on an interstellar expedition through a newly discovered wormhole near Saturn, desperately searching for three potentially habitable planets to ensure humanity’s survival before time slips away completely.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCilc8Xuq4pSp50nF70KEmdhRERAHfk3Nxdux2KVgg0Fr-3pc258gGQUog6urDXvFtK2ibmUal7WrrIWz9nC2rERLyISlxTFi4V8qbMebb7IQZKKFhH8PpGLlIYEszZw_ahz2rUySeQxXmW_EQUYWrF_S4nddbUUUeJEkDIdXzBpdIopIIiMKAM7k_JP2DXc-hVTnUtoJA3IfCbeOHxob5GFMMB4qyRb4QRhECZjLFMSOkAZXCChKW8",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUOgv9yz_3DQX1fTFYydTIsYfVF-fvHNZiVhKltsHN3PvjKLMXWksC0vxB-rQFWgk9TpU6WGQyFqqlOetiytLOefpkZJtECFRmIadfyl9NoC1qyz89_7Q6_QEuPFuUsqeu6J-IxqrRrif8L8vHYEuOdW-8csV1vtikQJvSLwVrsIwz32uSbvNHcxbvKHCHxovhZeVF3DMaYHjaDJyBPEq1-V7f2eUIjFGQRrqlyduHjcVjTSE6Qwv0",
    release_date: "2014-11-05",
    vote_average: 8.7,
    vote_count: 35400,
    runtime: 169,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 12, name: "Adventure" }, { id: 18, name: "Drama" }],
    director: "Christopher Nolan",
    cast: [
      { id: 10297, name: "Matthew McConaughey", character: "Joseph Cooper", profile_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuDrw9rq5g-zvayK9KQjqEVDqEoW9F7wESDB2yWwlgLgqgthod_EAx4YsqjGKrsFp3Dj_nE42keXM00mBu8SOIq1-pFOpOFrVXnE6w-R2hWU7PH2OWjgwcpUaHuSa3oe6s_zWVCidljCFc0IVDzA_oIG504em2GdsQPkzwMMrf3KT_CjFy3WY9nEBFVfQX--MR5bOJ-CKo9KyxRGDAOK5Yl8lvQDeAUY5ZnxY9-4rjsdu-r3ljYuCvrn" },
      { id: 1813, name: "Anne Hathaway", character: "Dr. Amelia Brand", profile_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRoX-kcJdchgnTxlg1M1wsrcPMXSuhZEAHCc32xKCV7MdKP6fW3A_PmkT9GZjQQSMJn2nR6U40aEZi1DyMMyeUkQPtLpEbgvVkiv6qhPrItCpyf-HaT5LPAV1T9rKHAQBKgc37ZxnC_aYKa23TtWspEOhz0lRbYxUN9UBg2ShytcGSz-6-8EDRRXvqBkBKbNXy0oimEiBK5tOihzLc3BE380Dyimu0PKirUYtFSl9XnrSuad3aNxi4" },
      { id: 83002, name: "Jessica Chastain", character: "Murphy Cooper", profile_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdYGQdTntPRINWXF7rU_fytSJJYfXsfBYKIjE5VWWRB8SHsqzVi0ZiNf8KE-F3NYaxo3RwXB850PL1ZTm1wlzLeoWzaZrWEVv5VBANvjhs-pkzw-w0Poz-aWsCjq1awQlTSiA3CNxt0BaM4OroZk2aAdD3BTRkNgEzEuX0UNBtbil9bxXS69xRx6-SEIGRdUOtCFKFJKRygAYDp2akvBHdqe25HFar0FQnwnPz0G68L14hF8z7t61D" },
      { id: 3895, name: "Michael Caine", character: "Professor John Brand", profile_path: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150" }
    ],
    trailer_key: "zSWdZVtXT7E",
    certification: "PG-13",
    editorialBadge: "99% Match of the Day",
    popularity: 96.0
  },
  {
    id: 335984,
    title: "Blade Runner 2049",
    tagline: "The key to the future is finally unearthed.",
    overview: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCZxOhRq2ocKlfVh6tkkBBGdFX4bDitWT4PvWNUbatPSdE8Mcciu4oYYptVorhn9EsAsvybcLX50OJfo53X6sGpoNx-JwEG1H6_B2LSMRvo3C0ukCLbFHJp2I_0hLZcUW7QCbiw0BnA5epWVHa6aJxD_wVjJvP96gmm14TDHMkQsDmgp1mEAJn4KVFr677rARIQ_II_lSb_toI_8uaVDySmk1mfY0DSd8EJ9w0csO13b8pXEt3XlIOa",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuD6NdcIVBloS2mdaPtZ74a1XwXDkFs9tGJEQL5ymOC4SNkFszANyUxSXF9kglrGoDMnVLCU4nW0KXk7QLn6rGmRqlD5kttS_lpPONqp7ZWaJeVAe980C99VjJDx-MBSbxNaJNE8io_vdy7wwM-e9x8UIw-SWTX7PJ3qrqfefNd7MVECoKcKuzXSrVuZ_B_GSSaZR_LzsTYGwy0guSXzlncdgoADKXtIFvm6_JzqLN-kkg4PbWn7ANt1",
    release_date: "2017-10-04",
    vote_average: 8.8,
    vote_count: 13200,
    runtime: 164,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 9648, name: "Mystery" }, { id: 18, name: "Drama" }],
    director: "Denis Villeneuve",
    cast: [
      { id: 30614, name: "Ryan Gosling", character: "Officer K", profile_path: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150" },
      { id: 3, name: "Harrison Ford", character: "Rick Deckard", profile_path: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150" },
      { id: 1373737, name: "Ana de Armas", character: "Joi", profile_path: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150" }
    ],
    trailer_key: "gCcx85zbxz4",
    certification: "R",
    popularity: 94.0
  },
  {
    id: 329865,
    title: "Arrival",
    tagline: "Why are they here?",
    overview: "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuDxVDiTNI58LG2MizS8wrziaA9LqlL1PfZCD2mDGvQoUb_RaPUEtVNJgcRq0sE4dYzMIBdPNovJ_hZNI7tSHBoRT963S9hlggUMaq81MK5WDZh2Q8VmD0vb65yHbUYVHUKC4a1TYIk5nnjPbGCLEObvbZubRdrqcBnzm-2oENkuywasBEokWjuuBkEyoBcnK_G-AvuFH9g5zUUdCJTsOuwILFUKDd12btivfqUIkk3RE4sLLvikO3Be",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuB6Cam8VfE_OUu1ao7A7PnMvKUoTS_7c5j2LCik1Ct_eMjcMwUXz2Gx2NidZAW3JruWoLpF_vvNQZLT51Ru4kGVVWDHnEwDZWiSr8n1dV7zeXruwu62H-XfGBqUzxpPE97JQMwL3-xME3nppwRqegdgdtPkH_knXfXoPltEbgLpirceWQSGUP0SzinExSN5AlB8QCWrWc1Dc2Y-hYe3YroEZqV5-nnwRkQ1VIzxZzFfahP1RuQTOnB-",
    release_date: "2016-11-10",
    vote_average: 7.9,
    vote_count: 16900,
    runtime: 116,
    genres: [{ id: 18, name: "Drama" }, { id: 878, name: "Sci-Fi" }, { id: 9648, name: "Mystery" }],
    director: "Denis Villeneuve",
    cast: [
      { id: 9273, name: "Amy Adams", character: "Dr. Louise Banks", profile_path: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150" },
      { id: 17604, name: "Jeremy Renner", character: "Ian Donnelly", profile_path: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150" }
    ],
    trailer_key: "tFMo3UJ4B4g",
    certification: "PG-13",
    popularity: 91.0
  },
  {
    id: 872585,
    title: "Oppenheimer",
    tagline: "The world forever changes.",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II, examining the moral weight and devastating fallout of human ambition.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuDN6hC8HB4LpSfWee25PfGCFMvRYBTteX6xe945TqGsMwPlVJhAmWbi0Q58V7JfNNX2zpJkQGOQKFOyXhUaUNP4Nk_HAW4fH315fLz65OVsMYTW3InhEtiSg40NXdwbuqs3I838fiCZownHZi9jG2TxHdfXiZCyr-Jj-VmzrlR2uUZxnePSXI0gJ1DzFl5UN0lYn7lZLmxnyGdKLn0-Mjav27GmfPc0IgmdyDGgcmL9xHivksasTGbn",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBmsmwKhMNqIVVutJO0pEcx0zjSwiSB-BN-OAP16aqr16Tjz8FQ9OVdtWhaYttMErrvFkSKwuJPzySxcJDNcwskKyx5HsevSGk_-1jkfIj1xxLr4Ge5sqgeKnZ8uzMVIFIqaV1KX7qLMLL4mm6O9WNSHyRpqMuKwknyiVzeyvJKI2AbIWs8R1JD7naZZogxlePg97a3ri5oTV09NnFMjsMNxDhYYNoiYN2K3frQKFQkLJvRLq9AR3fA",
    release_date: "2023-07-19",
    vote_average: 8.9,
    vote_count: 9400,
    runtime: 180,
    genres: [{ id: 18, name: "Drama" }, { id: 36, name: "History" }, { id: 53, name: "Thriller" }],
    director: "Christopher Nolan",
    cast: [
      { id: 2037, name: "Cillian Murphy", character: "J. Robert Oppenheimer", profile_path: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150" },
      { id: 5081, name: "Emily Blunt", character: "Katherine 'Kitty' Oppenheimer", profile_path: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150" },
      { id: 1892, name: "Matt Damon", character: "Leslie Groves", profile_path: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150" }
    ],
    trailer_key: "uYPbbksJxIg",
    certification: "R",
    editorialBadge: "IMAX",
    popularity: 95.0
  },
  {
    id: 792307,
    title: "Poor Things",
    tagline: "She's like nothing you've ever seen.",
    overview: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAzqjF_A5T1IM4ggrTYp2uX3tfiv7bjZyxIE_bCGBfDoXYlnU8pne8rfrjYsyNMKWH0Hv8RH9t0mqyywnqUoDRLrmS2GhLe7PLIvF3NWcUeuQHgzlNpK2H_nafm9Yo-Be9iLe1jq_lLHzzw89KwF2dAjbguU4H1Efc-fdapP8EJzNAp1PE2soQx-PM-nZM4fj9_m2QoaBeyTFJ_J1YUOa_bFL5yhO0Mjmehkqgw5TvCHJG3MD9RNzNX",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAzqjF_A5T1IM4ggrTYp2uX3tfiv7bjZyxIE_bCGBfDoXYlnU8pne8rfrjYsyNMKWH0Hv8RH9t0mqyywnqUoDRLrmS2GhLe7PLIvF3NWcUeuQHgzlNpK2H_nafm9Yo-Be9iLe1jq_lLHzzw89KwF2dAjbguU4H1Efc-fdapP8EJzNAp1PE2soQx-PM-nZM4fj9_m2QoaBeyTFJ_J1YUOa_bFL5yhO0Mjmehkqgw5TvCHJG3MD9RNzNX",
    release_date: "2023-12-07",
    vote_average: 8.0,
    vote_count: 4200,
    runtime: 141,
    genres: [{ id: 35, name: "Comedy" }, { id: 10749, name: "Romance" }, { id: 878, name: "Sci-Fi" }],
    director: "Yorgos Lanthimos",
    cast: [
      { id: 54693, name: "Emma Stone", character: "Bella Baxter", profile_path: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150" },
      { id: 103, name: "Mark Ruffalo", character: "Duncan Wedderburn", profile_path: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150" }
    ],
    trailer_key: "RlbR5NUG43c",
    certification: "R",
    editorialBadge: "Oscar Nom",
    popularity: 88.0
  },
  {
    id: 666277,
    title: "Past Lives",
    tagline: "In-Yun: The ties between two people over lifetimes.",
    overview: "Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora's family emigrates from South Korea. Decades later, they are reunited in New York for one fateful week as they confront notions of destiny, love and the choices that make a life.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuA2zR_zG200jv3J9nLgO4_aAmm4Okjps3aMrivAgo91JtV4gRKRxxX9CGiVTnPanRJA8UmwIl12gpeJ0XQ2D1GGGsQsFz6vRZISlbDxSwLCvHsRVBRN8hIXzAXPlCTXO2sn8xQtacpD1nSBIpNtLdjUdIzZVp5CCp2DPthK3OI4HoDG1yN_L7_t__-72c3ZugwAoAVlIczy3iS3EZRGtPKoAJyX1gsKUGNq0k75HzxsxQPcpFANv3-i",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuA2zR_zG200jv3J9nLgO4_aAmm4Okjps3aMrivAgo91JtV4gRKRxxX9CGiVTnPanRJA8UmwIl12gpeJ0XQ2D1GGGsQsFz6vRZISlbDxSwLCvHsRVBRN8hIXzAXPlCTXO2sn8xQtacpD1nSBIpNtLdjUdIzZVp5CCp2DPthK3OI4HoDG1yN_L7_t__-72c3ZugwAoAVlIczy3iS3EZRGtPKoAJyX1gsKUGNq0k75HzxsxQPcpFANv3-i",
    release_date: "2023-06-02",
    vote_average: 7.9,
    vote_count: 2800,
    runtime: 106,
    genres: [{ id: 18, name: "Drama" }, { id: 10749, name: "Romance" }],
    director: "Celine Song",
    cast: [
      { id: 2470724, name: "Greta Lee", character: "Nora", profile_path: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150" },
      { id: 1391780, name: "Teo Yoo", character: "Hae Sung", profile_path: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150" }
    ],
    trailer_key: "kA244xewjcI",
    certification: "PG-13",
    editorialBadge: "A24",
    popularity: 86.0
  },
  {
    id: 466420,
    title: "The Zone of Interest",
    tagline: "The banality of evil.",
    overview: "Auschwitz commandant Rudolf Höss and his wife Hedwig strive to build a dream life for their family in a house and garden next to the camp.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBndLe_SRaK9ApGPeZrGSo7IZ1Pt2hRrRMKkepLWLDYXtaOI5V-7mAzBG7p5oolJrE6qj0Ozf2BpQ-B1z0Q1kLeR0v2hLj_cIZ7MlE4Do7Qwd37I6LLyRda3Q3HrYASJLg4DsAYnWJ7LvfMSniuLMG8ubqhVFWWBBUpxhtK3Vqtzl1DJbREqqDBB1kS3UcrRakfA8edEyHdGDiBhchy9ISiFeYhqhZw0lRiGYvqwGlQm_i8MDbBWort",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBndLe_SRaK9ApGPeZrGSo7IZ1Pt2hRrRMKkepLWLDYXtaOI5V-7mAzBG7p5oolJrE6qj0Ozf2BpQ-B1z0Q1kLeR0v2hLj_cIZ7MlE4Do7Qwd37I6LLyRda3Q3HrYASJLg4DsAYnWJ7LvfMSniuLMG8ubqhVFWWBBUpxhtK3Vqtzl1DJbREqqDBB1kS3UcrRakfA8edEyHdGDiBhchy9ISiFeYhqhZw0lRiGYvqwGlQm_i8MDbBWort",
    release_date: "2023-12-15",
    vote_average: 7.8,
    vote_count: 2100,
    runtime: 105,
    genres: [{ id: 18, name: "Drama" }, { id: 36, name: "History" }, { id: 10752, name: "War" }],
    director: "Jonathan Glazer",
    trailer_key: "r-vfg3KkV54",
    certification: "PG-13",
    editorialBadge: "Grand Prix",
    popularity: 85.0
  },
  {
    id: 577922,
    title: "Tenet",
    tagline: "Time runs out.",
    overview: "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuB44b7maXRs4uZyaDATefdN74wxZ07jered_7wVZWrANetQlxJerov68LsWLNtOJddKwml-R4zxowOFz2yOqjTmHFhzskp2-cdFFW83ix6ntWl67z3rxDflHHjeOBwQmMUy7WcLTruAnzYNb97gwHqTDj7UjmQImFffETgPecHhBRoX32mhShaKsrRbgcyTajXOGm_R2M8vwfQkKkU2WskgOpbmhFhDOQBEjTGpbwjKa3R2wOEyin29",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuB44b7maXRs4uZyaDATefdN74wxZ07jered_7wVZWrANetQlxJerov68LsWLNtOJddKwml-R4zxowOFz2yOqjTmHFhzskp2-cdFFW83ix6ntWl67z3rxDflHHjeOBwQmMUy7WcLTruAnzYNb97gwHqTDj7UjmQImFffETgPecHhBRoX32mhShaKsrRbgcyTajXOGm_R2M8vwfQkKkU2WskgOpbmhFhDOQBEjTGpbwjKa3R2wOEyin29",
    release_date: "2020-08-22",
    vote_average: 7.3,
    vote_count: 9100,
    runtime: 150,
    genres: [{ id: 28, name: "Action" }, { id: 878, name: "Sci-Fi" }, { id: 53, name: "Thriller" }],
    director: "Christopher Nolan",
    trailer_key: "LdOM0x0WV3o",
    certification: "PG-13",
    popularity: 90.0
  },
  {
    id: 11324,
    title: "Shutter Island",
    tagline: "Someone is missing.",
    overview: "World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from a hospital for the criminally insane, but his efforts are compromised by his own troubling memories and cryptic clues.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuC10JASkEYVj5dnF0ZvDW2rnzcEFuYkZ6CreXj1kwI8zHC8KJrbmqLHnDoVfhYDSkqFJ5kt2J5wN8gIrGQpogglhGajcrnCv6azJvVd5a4tkUktv59f7pLkEoIVgmyd-s-ldtAbwWbxPb4a_DYgaQnnP2-4CHgj3IBLy8rQm2B9STR-O94wEvpLbPo-CyiwclfwwsvU7KBbGcxeY1BVuKf88-gZ9zaxe5tjb5wdmNZNW17TA09jOkHb",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuC10JASkEYVj5dnF0ZvDW2rnzcEFuYkZ6CreXj1kwI8zHC8KJrbmqLHnDoVfhYDSkqFJ5kt2J5wN8gIrGQpogglhGajcrnCv6azJvVd5a4tkUktv59f7pLkEoIVgmyd-s-ldtAbwWbxPb4a_DYgaQnnP2-4CHgj3IBLy8rQm2B9STR-O94wEvpLbPo-CyiwclfwwsvU7KBbGcxeY1BVuKf88-gZ9zaxe5tjb5wdmNZNW17TA09jOkHb",
    release_date: "2010-02-14",
    vote_average: 8.2,
    vote_count: 23500,
    runtime: 138,
    genres: [{ id: 18, name: "Drama" }, { id: 9648, name: "Mystery" }, { id: 53, name: "Thriller" }],
    director: "Martin Scorsese",
    trailer_key: "5iaYLCiq5RM",
    certification: "R",
    popularity: 88.0
  },
  {
    id: 1124,
    title: "The Prestige",
    tagline: "Are you watching closely?",
    overview: "A mysterious story of two magicians whose intense desire to uncover each other's secrets leads to deadly rivalry, fantastic trickery, and tragic consequences.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwvPODcL6r2tnEvBQHKagBTqBFn94Y6LFlkfTcoXtP5NneMfoKwrXUIPQVdfAo45eJpmtGfjR-yB_ftKcHgbarqqM5QJXY9khfpF_pyx0C0JsS0IN4qoUb0WwFiz2CHiZY2BY7bEU-LtWc5DnqRyOuWULIub8yBjUQDRMkCfkxfemyGbD3psKymLtPVCQxMFi_vlBo7ahZsVpA2WdTs0KmiyZpDV1c46vGCZGGyRVCltvRUPD2fAYF",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwvPODcL6r2tnEvBQHKagBTqBFn94Y6LFlkfTcoXtP5NneMfoKwrXUIPQVdfAo45eJpmtGfjR-yB_ftKcHgbarqqM5QJXY9khfpF_pyx0C0JsS0IN4qoUb0WwFiz2CHiZY2BY7bEU-LtWc5DnqRyOuWULIub8yBjUQDRMkCfkxfemyGbD3psKymLtPVCQxMFi_vlBo7ahZsVpA2WdTs0KmiyZpDV1c46vGCZGGyRVCltvRUPD2fAYF",
    release_date: "2006-10-19",
    vote_average: 8.5,
    vote_count: 15400,
    runtime: 130,
    genres: [{ id: 18, name: "Drama" }, { id: 9648, name: "Mystery" }, { id: 878, name: "Sci-Fi" }],
    director: "Christopher Nolan",
    trailer_key: "o4gHCmTQDVI",
    certification: "PG-13",
    popularity: 89.0
  },
  {
    id: 77,
    title: "Memento",
    tagline: "Some memories are best forgotten.",
    overview: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty, however, of locating his wife's killer is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCrT0UXbkzre4uq3OW9Fs_3N45Jz24zSI-T6TDH09f8YASeuOmaF1Fl4x3SgrWV-nKpazV_4b7APQ0RsYm69jqqAdNF6gJ54ssFbao11M_P1xfpuBYE12fpPQUMkHnfd1UbImpyC_e3bqU21znhLjSOuNef53xSM-5b5NX6saaxXP5jHxG6FaPX_w244UzwTNN6bZlnqckh_Ly3UzWacewtFIxtablcWeJGhO_sTBYMIe9QLh-hIxMm",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCrT0UXbkzre4uq3OW9Fs_3N45Jz24zSI-T6TDH09f8YASeuOmaF1Fl4x3SgrWV-nKpazV_4b7APQ0RsYm69jqqAdNF6gJ54ssFbao11M_P1xfpuBYE12fpPQUMkHnfd1UbImpyC_e3bqU21znhLjSOuNef53xSM-5b5NX6saaxXP5jHxG6FaPX_w244UzwTNN6bZlnqckh_Ly3UzWacewtFIxtablcWeJGhO_sTBYMIe9QLh-hIxMm",
    release_date: "2000-10-11",
    vote_average: 8.4,
    vote_count: 14200,
    runtime: 113,
    genres: [{ id: 9648, name: "Mystery" }, { id: 53, name: "Thriller" }],
    director: "Christopher Nolan",
    trailer_key: "4CV41hoyS8A",
    certification: "R",
    popularity: 87.0
  },
  {
    id: 438631,
    title: "Dune: Part One",
    tagline: "It begins.",
    overview: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBb-VkQ4Op5a-tts4w4i3KY-l6mqZJUuWcjjSuMed1-buK4lAH6qOUKDpBVo5r0CyTtrEGm9Jy6Kq7EMuR-ZhpDkJveAH6RwUmlWcKZRnV4RBC0ZEZPvkYWQg7gfpqyXsb1QWyVR2t7XN9Oa5FAQuswopZggGM1ZoHipOGHI2N5WS12SlXcu9N22PomdD-TGV7MUrrtQBoJ83prMSpKmuUdxYf-v-9xQRvfPhtHnW4pew7EIjEOZE9s",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBb-VkQ4Op5a-tts4w4i3KY-l6mqZJUuWcjjSuMed1-buK4lAH6qOUKDpBVo5r0CyTtrEGm9Jy6Kq7EMuR-ZhpDkJveAH6RwUmlWcKZRnV4RBC0ZEZPvkYWQg7gfpqyXsb1QWyVR2t7XN9Oa5FAQuswopZggGM1ZoHipOGHI2N5WS12SlXcu9N22PomdD-TGV7MUrrtQBoJ83prMSpKmuUdxYf-v-9xQRvfPhtHnW4pew7EIjEOZE9s",
    release_date: "2021-09-15",
    vote_average: 8.0,
    vote_count: 10400,
    runtime: 155,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 12, name: "Adventure" }],
    director: "Denis Villeneuve",
    trailer_key: "n9xhJrPXop4",
    certification: "PG-13",
    popularity: 92.0
  },
  {
    id: 264660,
    title: "Ex Machina",
    tagline: "There is nothing more human than the will to survive.",
    overview: "Celebrated programmer Caleb Smith wins a contest to spend a week at the private mountain estate of Nathan Bateman, the reclusive CEO of his company. Caleb discovers that Nathan has selected him to evaluate the capabilities and consciousness of Ava, a sentient android.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCb4YW1IaI29melHnx8bt9YE-uTGKekP548A8ZTYunqxbNWXvMoyRF7eVxRkj96BFUfrIXL4JK7kT1bOZv9xihoxLtUFzpRiLjxqc5oaXXK2UdSy6h3iTrg8mlxI89YEI48_e6KZN1_QsNv7dZ_hag31ou_-UNFRljmNwZVKhPmUbmNZGXII3Wi9yyEs5FN5A0gFNOyp-grggCXIQYvZkWRzaG8RFhMd9zkMwuovzz89ir9qXz4UK_4",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCb4YW1IaI29melHnx8bt9YE-uTGKekP548A8ZTYunqxbNWXvMoyRF7eVxRkj96BFUfrIXL4JK7kT1bOZv9xihoxLtUFzpRiLjxqc5oaXXK2UdSy6h3iTrg8mlxI89YEI48_e6KZN1_QsNv7dZ_hag31ou_-UNFRljmNwZVKhPmUbmNZGXII3Wi9yyEs5FN5A0gFNOyp-grggCXIQYvZkWRzaG8RFhMd9zkMwuovzz89ir9qXz4UK_4",
    release_date: "2014-12-16",
    vote_average: 7.7,
    vote_count: 12800,
    runtime: 108,
    genres: [{ id: 18, name: "Drama" }, { id: 878, name: "Sci-Fi" }, { id: 9648, name: "Mystery" }],
    director: "Alex Garland",
    trailer_key: "EoQuVnKhxaM",
    certification: "R",
    popularity: 87.0
  },
  {
    id: 670292,
    title: "The Creator",
    tagline: "This is a fight for our very existence.",
    overview: "Amid a future war between the human race and the forces of artificial intelligence, Joshua, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHRmGq1-SJlWBsdtZQTk2FpMPvwGdGlyg6R6VtZFW7zSL0uFtEJhKw_ErnDi9VglPbYnMtgaY9vkIz7lCDB5VgucSvfkxmwMEUgI5nDEgZURmKKsljQDkvWfi-yPZa9DdVHHyhr5tq9hV31qKOI4261g8HqkmegrFm31uFmGz8lyzOsloojic7DbsGsONH8SxLPgSu9G2Y05dbVRgTEoNernhaBvdqQ5LVe3PVDH_3uZ5r360j5rte",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHRmGq1-SJlWBsdtZQTk2FpMPvwGdGlyg6R6VtZFW7zSL0uFtEJhKw_ErnDi9VglPbYnMtgaY9vkIz7lCDB5VgucSvfkxmwMEUgI5nDEgZURmKKsljQDkvWfi-yPZa9DdVHHyhr5tq9hV31qKOI4261g8HqkmegrFm31uFmGz8lyzOsloojic7DbsGsONH8SxLPgSu9G2Y05dbVRgTEoNernhaBvdqQ5LVe3PVDH_3uZ5r360j5rte",
    release_date: "2023-09-27",
    vote_average: 6.8,
    vote_count: 3100,
    runtime: 133,
    genres: [{ id: 28, name: "Action" }, { id: 12, name: "Adventure" }, { id: 878, name: "Sci-Fi" }],
    director: "Gareth Edwards",
    trailer_key: "ex3C1-5Dhb8",
    certification: "PG-13",
    popularity: 84.0
  },
  {
    id: 220289,
    title: "Coherence",
    tagline: "Rearrange your reality.",
    overview: "On the night of an astronomical anomaly, eight friends at a dinner party experience a troubling chain of reality-bending events. Part relationship drama and part mind-bending sci-fi, Coherence is a tightly woven mystery.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdjDParJ4sOsfdHgJYK5QEFMA-kUg3FpPP11PUPd1VUY_Kfp3THzRlpDdOsY2_4fiMKdl_7IyjQxibuOT6DX1XDyguywdy3a9AjlQzPh7kcucN-7mmB96kQnIToaPWJQTcw8lgw8-QeeY4RH06dsRD6zTvSxPA8CcIWlqUq4CPV8GhMxxVog_kvh63b0HQpYmo4n29rubzMqhqqPJZdsjb-mHJUWg6GIS_k1nFqsfkq79n8cEjZNFu",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdjDParJ4sOsfdHgJYK5QEFMA-kUg3FpPP11PUPd1VUY_Kfp3THzRlpDdOsY2_4fiMKdl_7IyjQxibuOT6DX1XDyguywdy3a9AjlQzPh7kcucN-7mmB96kQnIToaPWJQTcw8lgw8-QeeY4RH06dsRD6zTvSxPA8CcIWlqUq4CPV8GhMxxVog_kvh63b0HQpYmo4n29rubzMqhqqPJZdsjb-mHJUWg6GIS_k1nFqsfkq79n8cEjZNFu",
    release_date: "2013-09-19",
    vote_average: 8.1,
    vote_count: 2400,
    runtime: 89,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 9648, name: "Mystery" }, { id: 53, name: "Thriller" }],
    director: "James Ward Byrkit",
    trailer_key: "sEceDz1Erq8",
    certification: "Not Rated",
    editorialBadge: "Hidden Gem",
    surpriseScore: 96,
    popularity: 76.0
  },
  {
    id: 17431,
    title: "Moon",
    tagline: "The last place you'd ever expect to find yourself.",
    overview: "Astronaut Sam Bell approaches the end of a three-year solo stint on the Moon, where he extracts helium-3 to send back to Earth. As his return home nears, he suffers an accident and discovers a shocking secret.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuDZLMjbSKpaVv6R9S8ItJdY7gu3HLRESAcWtRmO85tbBhDJo5RukP3GpMEbs3N8z85tNUV2t222mwEj1XUXoDx9IbvCy-tsh-VBASj1UzfszowEHLb3J9oE6_mXMerno79aANFU_PbYZzcnwyGPJQiBGU1u6FgnYLVIuUzIzH8cbrK7SL-oR_pwFi2F2oGg7r972FPp9m53iyGUiVgyCpkqTZ2BXZMhfpn3yTEX_z_HvOFaxiVbLdi7",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuDZLMjbSKpaVv6R9S8ItJdY7gu3HLRESAcWtRmO85tbBhDJo5RukP3GpMEbs3N8z85tNUV2t222mwEj1XUXoDx9IbvCy-tsh-VBASj1UzfszowEHLb3J9oE6_mXMerno79aANFU_PbYZzcnwyGPJQiBGU1u6FgnYLVIuUzIzH8cbrK7SL-oR_pwFi2F2oGg7r972FPp9m53iyGUiVgyCpkqTZ2BXZMhfpn3yTEX_z_HvOFaxiVbLdi7",
    release_date: "2009-06-12",
    vote_average: 7.8,
    vote_count: 5300,
    runtime: 97,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 18, name: "Drama" }],
    director: "Duncan Jones",
    trailer_key: "twuScTcDP_Q",
    certification: "R",
    editorialBadge: "Hidden Gem",
    popularity: 79.0
  },
  {
    id: 14337,
    title: "Primer",
    tagline: "What happens if it actually works?",
    overview: "Two intellectual engineers inadvertently discover causal time-loop anomalies while working on their garage startup invention, leading to unexpected paranoia and escalating paradoxes.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCoTMGar2SGFg6Z82T2LI7D7iqaODvnZu0Rt8SRVgA0orgq_EuOupEX9IVaA-7zft18WFqvxYdXk7Xy5iQNU7WMyZ6-e4lKs9NR6-Ca0BPwzMVhWbh9LSw8698QkUblyRUPfr8lSU4z_GLSdsnotMzeV5gwUxYrShx3GIehDSIEX1OOHq80yknqYaltoQfpXlt7cPe2VPv6E0LBkkLWndi5jFAWSrjbuMf0llQ9IMc23ILBnUdE3oSO",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuCoTMGar2SGFg6Z82T2LI7D7iqaODvnZu0Rt8SRVgA0orgq_EuOupEX9IVaA-7zft18WFqvxYdXk7Xy5iQNU7WMyZ6-e4lKs9NR6-Ca0BPwzMVhWbh9LSw8698QkUblyRUPfr8lSU4z_GLSdsnotMzeV5gwUxYrShx3GIehDSIEX1OOHq80yknqYaltoQfpXlt7cPe2VPv6E0LBkkLWndi5jFAWSrjbuMf0llQ9IMc23ILBnUdE3oSO",
    release_date: "2004-10-08",
    vote_average: 6.8,
    vote_count: 2200,
    runtime: 77,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 18, name: "Drama" }, { id: 53, name: "Thriller" }],
    director: "Shane Carruth",
    trailer_key: "x_HHnXeMWT0",
    certification: "PG-13",
    editorialBadge: "Cult Classic",
    popularity: 74.0
  },
  {
    id: 273481,
    title: "Sicario",
    tagline: "The line is crossed.",
    overview: "An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAXjPv2e9EKbP9_hO29WfkmsLpcY0tAm3CSv3e4sNWJFJFROCuBL5nZkkDgzoX6hH2QSmyAAho4u0ka9t95b_p6vlSclhnCUVhQqOGqzZIEiA9NGHi_DYZdY1hgM4I3bTi0u5kCvcMFAE7KGCoPAJwqMJ1EBtg3WEpTwGQr5OcbpLH132T8_3VxxmDPw3_s_nLWRSOWejU_pQ4qZgplt0tkrEox0iAYiyjv3jRr49hNnhjJK0vrblAY",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAXjPv2e9EKbP9_hO29WfkmsLpcY0tAm3CSv3e4sNWJFJFROCuBL5nZkkDgzoX6hH2QSmyAAho4u0ka9t95b_p6vlSclhnCUVhQqOGqzZIEiA9NGHi_DYZdY1hgM4I3bTi0u5kCvcMFAE7KGCoPAJwqMJ1EBtg3WEpTwGQr5OcbpLH132T8_3VxxmDPw3_s_nLWRSOWejU_pQ4qZgplt0tkrEox0iAYiyjv3jRr49hNnhjJK0vrblAY",
    release_date: "2015-09-17",
    vote_average: 7.7,
    vote_count: 8900,
    runtime: 121,
    genres: [{ id: 28, name: "Action" }, { id: 80, name: "Crime" }, { id: 18, name: "Drama" }, { id: 53, name: "Thriller" }],
    director: "Denis Villeneuve",
    trailer_key: "G8tlEJI4Z-mx",
    certification: "R",
    popularity: 88.0
  },
  {
    id: 496243,
    title: "Parasite",
    tagline: "Act like you own the place.",
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAOJGpdZtVqo_YjKhJZJB4ORkqOmyQLKPcejYEYs0H10g69LGe9waeN5BgpLDrZdfyHxPLDc0hEPsW9FbIbtHu-aZAdUccwWgO2ZEjr1Q5DONJ4xth7nUIXKHy_roCVXFjGscyziyr2jKptUzFqxF8pmMy_HV1JTQkPwYowZkKI-stDCejusbLMSUkKCuU1_0UcyZwEBI6GyQgbOqns-nDUa9tscn0i3yoi4WuYmwj4we1ngw01IIAi",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuAOJGpdZtVqo_YjKhJZJB4ORkqOmyQLKPcejYEYs0H10g69LGe9waeN5BgpLDrZdfyHxPLDc0hEPsW9FbIbtHu-aZAdUccwWgO2ZEjr1Q5DONJ4xth7nUIXKHy_roCVXFjGscyziyr2jKptUzFqxF8pmMy_HV1JTQkPwYowZkKI-stDCejusbLMSUkKCuU1_0UcyZwEBI6GyQgbOqns-nDUa9tscn0i3yoi4WuYmwj4we1ngw01IIAi",
    release_date: "2019-05-30",
    vote_average: 8.5,
    vote_count: 18000,
    runtime: 132,
    genres: [{ id: 35, name: "Comedy" }, { id: 53, name: "Thriller" }, { id: 18, name: "Drama" }],
    director: "Bong Joon-ho",
    trailer_key: "5xH0hhMBQZk",
    certification: "R",
    popularity: 96.0
  },
  {
    id: 244786,
    title: "Whiplash",
    tagline: "The road to greatness can take you to the edge.",
    overview: "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, pushing the limits of physical and emotional endurance.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuC0-XGuHy0Jm_doBsdBcivYcBVUNVpNrVwdZYZRYfUkg9PxBk6feGzuERjv1UQGjxHDgLOjNf5xQAsvC-_dlqKCvhySKvHORcZ_h51M2SUzXi5Hj8tvTSIJDUq9zxRQcmUxWWi-n9Ugu1RA3JWfFQvYL4qCSjGaCRPyzYZWuqTZk2cxqOwe2dE-PjhUQDfTp6-oi8YcJfB6DA6XdCKmE1KHkfLnUDhfzp71jDUOYE5qZb5qWhzMIqeI",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuC0-XGuHy0Jm_doBsdBcivYcBVUNVpNrVwdZYZRYfUkg9PxBk6feGzuERjv1UQGjxHDgLOjNf5xQAsvC-_dlqKCvhySKvHORcZ_h51M2SUzXi5Hj8tvTSIJDUq9zxRQcmUxWWi-n9Ugu1RA3JWfFQvYL4qCSjGaCRPyzYZWuqTZk2cxqOwe2dE-PjhUQDfTp6-oi8YcJfB6DA6XdCKmE1KHkfLnUDhfzp71jDUOYE5qZb5qWhzMIqeI",
    release_date: "2014-10-10",
    vote_average: 8.5,
    vote_count: 14700,
    runtime: 106,
    genres: [{ id: 18, name: "Drama" }, { id: 10402, name: "Music" }],
    director: "Damien Chazelle",
    trailer_key: "7d_jQycdQGo",
    certification: "R",
    popularity: 91.0
  },
  {
    id: 62,
    title: "2001: A Space Odyssey",
    tagline: "An epic drama of adventure and exploration.",
    overview: "Humanity finds a mysterious object buried beneath the lunar surface and sets off on a quest to find its origins with the help of HAL 9000, the world's most advanced supercomputer.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuANqYBvRECqDz25pghPU8_pk5QB5oTGNESZJvnMa08IcpCYQ0OGE2U41N0qaWnTpVUraf6DKdRgFBJycsI4_dlTFky8DBJP5ayX5L_yZ7ZvRY6IU8371DuGhzMqp6f7NHG-JbydJ9DH6O_oZijZ3V1S33dhq7QPDCEjBaRWsttFPuoJSGgtEVzMcP-3NWasrn2PyK6OBcOiwUbmaBvebeJAo20moGhZRZJGa0VuC_My7IT46W35A6bq",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuANqYBvRECqDz25pghPU8_pk5QB5oTGNESZJvnMa08IcpCYQ0OGE2U41N0qaWnTpVUraf6DKdRgFBJycsI4_dlTFky8DBJP5ayX5L_yZ7ZvRY6IU8371DuGhzMqp6f7NHG-JbydJ9DH6O_oZijZ3V1S33dhq7QPDCEjBaRWsttFPuoJSGgtEVzMcP-3NWasrn2PyK6OBcOiwUbmaBvebeJAo20moGhZRZJGa0VuC_My7IT46W35A6bq",
    release_date: "1968-04-02",
    vote_average: 8.3,
    vote_count: 11000,
    runtime: 149,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 9648, name: "Mystery" }, { id: 12, name: "Adventure" }],
    director: "Stanley Kubrick",
    trailer_key: "oR_e9y-bka0",
    certification: "G",
    popularity: 89.0
  },
  {
    id: 686,
    title: "Contact",
    tagline: "If we are alone in the universe, it feels like an awful waste of space.",
    overview: "Dr. Ellie Arroway, after years of searching, finds conclusive radio proof of extraterrestrial intelligence sending plans for a mysterious machine that could transport a single traveler.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBNJiwoqwZ3rNhKlXq8dbm16V9yXCNzrZmZeXe8qvGlG2Hoou_vO0U0l53I9U7ylOcA2KD6m0uga9G14uZAEWGORCeaBt1zvnq9Wi97VcOlHXw6zuFn_pqUn4ho5T6QhLaO_gPxwCC3VIFiWd7kRPmSMjte0P_GkUXppAEdhykl-ZGEvVZhxo4Npn5hIE82higGJsrlVsTJrHKW2GQR0lEbsmcqVzGPXiB7MDetLY2kDNVN6b2MK9e8",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBNJiwoqwZ3rNhKlXq8dbm16V9yXCNzrZmZeXe8qvGlG2Hoou_vO0U0l53I9U7ylOcA2KD6m0uga9G14uZAEWGORCeaBt1zvnq9Wi97VcOlHXw6zuFn_pqUn4ho5T6QhLaO_gPxwCC3VIFiWd7kRPmSMjte0P_GkUXppAEdhykl-ZGEvVZhxo4Npn5hIE82higGJsrlVsTJrHKW2GQR0lEbsmcqVzGPXiB7MDetLY2kDNVN6b2MK9e8",
    release_date: "1997-07-11",
    vote_average: 7.5,
    vote_count: 4200,
    runtime: 153,
    genres: [{ id: 18, name: "Drama" }, { id: 878, name: "Sci-Fi" }, { id: 9648, name: "Mystery" }],
    director: "Robert Zemeckis",
    trailer_key: "SRoj3jK37Vc",
    certification: "PG",
    popularity: 82.0
  },
  {
    id: 419704,
    title: "Ad Astra",
    tagline: "The answers we seek are just outside our reach.",
    overview: "An astronaut undertakes a mission across a forgiving solar system to uncover the truth about his missing father and his doomed expedition that now threatens the universe.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBnX9jBi4MXI8Ky3xZ7QUNUwbJMXXlnV5jSCLH4xMDDRcRTCG0gHF2S0NvvRCecvvFTFr0veZHZ__CJMKWtBAQl6y9ZH2bWNgudGTLFNLp-cC_JFqJywAOKO-Bl6y1KXxNxgewW343BgGdtnY4E1ab-Dj5tZmh8zGjjNSa_q5aEO59DTvEcdfOlQDqK_mp2oyuQRQOxE3yZXz69eoF6oyaFpzdiitMN0lsx2IEWNfuA2c182UQIqSbt",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBnX9jBi4MXI8Ky3xZ7QUNUwbJMXXlnV5jSCLH4xMDDRcRTCG0gHF2S0NvvRCecvvFTFr0veZHZ__CJMKWtBAQl6y9ZH2bWNgudGTLFNLp-cC_JFqJywAOKO-Bl6y1KXxNxgewW343BgGdtnY4E1ab-Dj5tZmh8zGjjNSa_q5aEO59DTvEcdfOlQDqK_mp2oyuQRQOxE3yZXz69eoF6oyaFpzdiitMN0lsx2IEWNfuA2c182UQIqSbt",
    release_date: "2019-09-17",
    vote_average: 6.5,
    vote_count: 6100,
    runtime: 123,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 18, name: "Drama" }, { id: 12, name: "Adventure" }],
    director: "James Gray",
    trailer_key: "P6AaSMfXHbA",
    certification: "PG-13",
    popularity: 78.0
  },
  {
    id: 760161,
    title: "Licorice Pizza",
    tagline: "Growing up is a team sport.",
    overview: "The story of Alana Kane and Gary Valentine growing up, running around and falling in love in the San Fernando Valley, 1973.",
    poster_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBTA6fq8HWXUcZhfxZBL1LeR14NFZ885E5w7a1pEDZ_MMqSat92Yas4NWCFNQxUfa0tJclz4Mt9e1KM8avSuOEFpN6XVqX-gYxy3eKLl9OqxRzP5hFQldof_kTv-SwULvR1_V8CCUxJw5B5IcpZlWibkXla-BQmKuOLOzP47UJNYqZP-3TkScSAvSvkIl-TlVnuwDura7zD4rkDJR-h_i_f93guctsY_OaChkU38NsjdX8sPntW0fxC",
    backdrop_path: "https://lh3.googleusercontent.com/aida-public/AB6AXuBTA6fq8HWXUcZhfxZBL1LeR14NFZ885E5w7a1pEDZ_MMqSat92Yas4NWCFNQxUfa0tJclz4Mt9e1KM8avSuOEFpN6XVqX-gYxy3eKLl9OqxRzP5hFQldof_kTv-SwULvR1_V8CCUxJw5B5IcpZlWibkXla-BQmKuOLOzP47UJNYqZP-3TkScSAvSvkIl-TlVnuwDura7zD4rkDJR-h_i_f93guctsY_OaChkU38NsjdX8sPntW0fxC",
    release_date: "2021-11-26",
    vote_average: 7.0,
    vote_count: 2100,
    runtime: 133,
    genres: [{ id: 35, name: "Comedy" }, { id: 18, name: "Drama" }, { id: 10749, name: "Romance" }],
    director: "Paul Thomas Anderson",
    trailer_key: "ofnChv7V0iU",
    certification: "R",
    popularity: 77.0
  },
  {
    id: 101,
    title: "Léon: The Professional",
    tagline: "A story about innocence and deadly precision.",
    overview: "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée.",
    poster_path: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500",
    backdrop_path: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200",
    release_date: "1994-09-14",
    vote_average: 8.5,
    vote_count: 14000,
    runtime: 110,
    genres: [{ id: 80, name: "Crime" }, { id: 18, name: "Drama" }, { id: 28, name: "Action" }],
    director: "Luc Besson",
    trailer_key: "aWQjCqkWl-A",
    certification: "R",
    popularity: 84.0
  }
];
